Copying //UE4/Dev-Mobile to //UE4/Dev-Main (Source: //UE4/Dev-Mobile @ 4047413) #lockdown Nick.Penwarden #rb none
============================
  MAJOR FEATURES & CHANGES
============================

Change 3795481 by Nick.Shin

	HTML5 - disable SupportsScreenPercentage() - render the full screen

	otherwise, this is causing HTML5 screen to only render a portion of the screen and in black...
	- there may be another function is that not getting fired off "to render the screen" properly
	- this may be due to IsMobileHDR checks that are not fully accounted for the HTML5 platform

	#jira UE-52640  HTML5 only renders a black rectangle in the browser when launched

Change 3807007 by Nick.Shin

	HTML5 - remove webgl1 only precompile guards (UE4_HTML5_TARGET_WEBGL2)

	toolchain can "fallback" to webgl1 -- webgl2 functions in UE4 code are "if checked"/configured/setup at start up

	#jira UE-51267 WebGL1 fails to compile

Change 3822593 by Nick.Shin

	#jira UE-27141  Remove all #if PLATFORM_HTML5 from high level code

Change 3823512 by Nick.Shin

	#jira UE-27141  Remove all #if PLATFORM_HTML5 from high level code

Change 3824639 by Nick.Shin

	HTML5 - OSX - RunMacHTML5LaunchHelper.command

	- more helpful warning messages

	#jira UE-49861  A copied RunMacHTML5LaunchHelper.command gives unspecific Mono error

Change 3829092 by Josh.Adams

	- Updated UnrealRemote to 1.4.1

Change 3832708 by Chris.Babcock

	Allow UE4Commandline.txt in APK
	#jira
	#ue4
	#android

Change 3835867 by Nick.Shin

	HTML5 - code cleanup

	origial work was for: UE-27141 (Remove all #if PLATFORM_HTML5 from high level code)

	this exposed an issue that i totally forgot about (.../Engine/Source/Developer/... only does builds tools -- which does not make use of PLATFORM_XXX preprocessor)

	tested with HTML5 builds with QAGame project :: TM-ShaderModels map

	#jira UE-53524  UE4Editor Static Analysis Win64 (MSVC) - 1 repeat warning

Change 3839967 by Mi.Wang

	Override MaxObjectInGame on Android to save ~30M with the ObjectArray size.
	#Android

Change 3842022 by Mi.Wang

	Fix an AssetRegistry size calculation bug.

Change 3843552 by Sorin.Gradinaru

	UE-54139 Possible crash with new virtual keyboard on Android if suggestions not disabled

	#4.19
	#Android
	#jira UE-54139

	S8 on 7.0 is not hiding suggestions and disabling predictive input.  There are cases with this that can cause a crash.

	Fix:  On text change, downgrade to simple suggestions all the easy correction spans that are not a spell check span (remove android.text.style.SuggestionSpan.FLAG_EASY_CORRECT flags)

Change 3844210 by Nick.Shin

	HTML5 - filter out "windows/super" keys - these are not used in UE4

	- but, keycode are not the expected "91 or 92" values, SDL keys are "227 & 231" instead...

	#jira UE-54056  HTML5 crashes inside browser upon pressing windows key

Change 3844874 by Nick.Shin

	HTML5 - detect "SyntaxError: " and do a forced reload

	- an actual syntax error would be caught during compile time
	- this is usually error condition is usually seen when browser is running "old/partial" cached data and it's fairly safe to just reload the page

	#jira UE-54017  QAGame fails to launch properly on HTML5 Firefox 64 bit

Change 3846695 by Nick.Shin

	#jira UE-53524  UE4Editor Static Analysis Win64 (MSVC) - 1 repeat warning

Change 3847309 by Nick.Shin

	HTML5 - (not to) show virtual joystick

	- virtual joysticks are not shown by default-- and the mouse not captured
	- this now behaves like the win64 client version

	#jira UE-33854  Virtual Joysticks In HTML5 if Mobile/Tablet Project is chosen

Change 3847310 by Nick.Shin

	HTML5 - set controller axis and button max value in code instead of relying on emscripten_get_gamepad_status()

	- seems emscripten might be uninitialized by the time controlers are used...

	#jira UE-28513 - Using a controller in HTML5 causes error

Change 3850606 by Nick.Shin

	HTML5 - more static warning fix ups

	#jira UE-53524  UE4Editor Static Analysis Win64 (MSVC) - 1 repeat warning

Change 3850624 by Nick.Shin

	HTML5 - tell user/developer to show unsupported WebGL browsers on old hardware -- will need to try another browser

	note: using following jira to track progress:
	#jira UE-47066  Packaged HTML 5 Map Prompts for Firefox Update in Chrome

Change 3855610 by Sorin.Gradinaru

	UE-49173 Progress bar causes black screen on iOS

	#iOS
	#4.20
	#jira UE-49173

	The bug occurs on iOS with Metal, when the last Slate element to be draw in the scene is a ScrollBar with progress between 0 and 1.
	As a workaround, adding another widget (eg. button, image) in the Blueprint solves the problem.
	The bug can be reproduced by adding OutDrawElements.PushClip & OutDrawElements.PopClip in any SWidget::OnPaint.

	The solution is to disable the scissor
			RHICmdList.SetScissorRect(false, 0, 0, 0, 0);
	in FSlateRHIRenderingPolicy::DrawElements after the batch rendering

Change 3855652 by Sorin.Gradinaru

	iOS 3D browser

	UE-53248 Web Browser on a Widget Component is 2D when launching on to iOS

	#jira UE-53248
	#iOS
	#4.20

	Uses the same WebTexture from the WebBrowser plugin as the Android version.
	+ Code contributed by Juan.Belon from Alea S.r.l  at https://udn.unrealengine.com/questions/390166/3d-world-space-widget-is-being-rendered-in-screen.html

Change 3856174 by Nick.Shin

	HTML5 - python forking will still error while trying to terminate already terminated processes

	- added same "WindowsError code 5" handler found in subprocess.py

	#jira UE-51618  HTML5 fails to build, [Error 5] Access is denied

Change 3863322 by Sorin.Gradinaru

	UE-54317 DXT apps fail on first launch when 'For Distribution' enabled, Unsupported Texture Format

	#jira UE-54317
	#Android
	#4.19

Change 3878088 by Nick.Shin

	UEMOB-425 superceeds this jira

	#jira UE-25257  Mac HTML5 project crashes upon downloading expression HasFoundDataDirectory failed

Change 3884560 by Jack.Porter

	Fix logspam in FAVMoviePlayer
	#jira UE-54760

Change 3886533 by Mi.Wang

	Fix a potential crash that the VirtualKeyboardWidget has been hide while trying to use in gamethread.

Change 3889081 by Sorin.Gradinaru

	UE-54490 Android Startup Movie audio still playing when app paused, and after app resumed the movie is blackscreen until engine ticked.

	#Android
	#4.20
	#jira UE-54490

	Call ForceCompletion for the intial movie player on onPause.
	Call App Restart on Resume.

	Programmatically restarting an Android application basically consists in killing the current app, then using the launch intent as parameter for startActivity.

	This can be done only in onResume , which means that the movie player still has to be manually paused/stopped in onPause.
	I╞ve tried to kill the activity on onPause, tested on several devices, with various problems: the app doesn╞t restart anymore (onResume is not called) or the app is automatically sent to background (seems to be crashing when using the multitasking soft key).

Change 3890320 by Chris.Babcock

	Fix initializer ordering
	#jira UE-55189
	#ue4

Change 3958226 by Nick.Shin

	HTML5 disable memory poison tests

	and fix a bug during Realloc() // for Linux... and in turn for HTML5

	#jria none

Change 3958250 by Nick.Shin

	HTML5 - FText::FormatStr - skip if multi-threading not supported

	#jira none

Change 3968328 by Nick.Shin

	HTML5 CORS fixes

	still need datarouter.ol.epicgames.com fixes to completely solve these issues. (API server own estimates no later than mid-April)

	note: the following are all related:

	+ answerhub 756723 - HTML5 CORS / Access-Control-Allow-Headers
	+ answerhub 756942 - HTML5 CORS Issue to my Hosts API / Hosted Server
	+ UE-22285 - Session events are not generated for HTML5
	+ UE-19330 - HTML5 Analytics cross-origin request blocked header Access-Control-Allow-Origin missing

	#jira UE-19330

Change 3971405 by Nick.Shin

	HTML5 suppress double printing to console.log

	#jira none

Change 3978767 by Nick.Shin

	HTML5 CORS fixes

	note: the following are all related:

	+ answerhub 756723 - HTML5 CORS / Access-Control-Allow-Headers
	+ answerhub 756942 - HTML5 CORS Issue to my Hosts API / Hosted Server
	+ UE-22285 - Session events are not generated for HTML5
	+ UE-19330 - HTML5 Analytics cross-origin request blocked header Access-Control-Allow-Origin missing

	tested (against datarouter.ol.epicgames.com fixes) and found to be functional

	#jira UE-22285

Change 3981103 by Nick.Shin

	HTML5 - num pad keys crashes project

	match latest Engine/Source/Runtime/InputCore/Private/Linux/LinuxPlatformInput.cpp to HTML5PlatformInput.cpp
	also fix a HUD crash...

	#jira UE-54056  HTML5 crashes inside browser upon pressing windows key

Change 3983424 by Sorin.Gradinaru

	UE-57107 Attempting to load a streamed media source causes the app to become unresponsive when device is not connected to internet

	#jira UE-57107
	#Android
	#4.20

	The ANR is because the android.media.MediaExtractor.setDataSource(UrlPath) calls an underlying api which retries the download (10-30 times).

	Additional issue (all platforms): the MediaFrameworkTest/StreamSource_Infiltrator souce seems to have been removed (no longer at https://docs.unrealengine.com/latest/attachments/Engine/MediaFramework/HowTo/StreamMediaSource/Infiltrator%20Demo.mp4). According to the docs (https://docs.unrealengine.com/en-US/Engine/MediaFramework/HowTo/StreamMediaSource) the new location of the Sample Video is at https://dnnrz1gqa.blob.core.windows.net/portals/attachments/Engine/MediaFramework/HowTo/StreamMediaSource/Infiltrator%20Demo.mp4?sr=b&si=DNNFileManagerPolicy&sig=F%2BBpnYueeQTUTSW0nCRSrXEfr35LIawe7C3MQoe2%2FPI%3D

Change 3985248 by Nick.Shin

	HTML5 game window size

	add project setting drop down box to select canvas scaling mode

	#jira UE-46555  HTML5 game window does not scale with browser size

Change 3986190 by Sorin.Gradinaru

	UE-56076  Android Launch On "Running..." toast intermittently doesn't appear

	#jira UE-56076
	#Android
	#4.10

	When cancelling Launch on Device, always call CancelContinuations for the current task

Change 3986412 by Nick.Shin

	CIS error fix
	#jira none

Change 3987007 by Nick.Shin

	HTML5 fullscreen size fix

	- when using FIXED scale mode initially, there's some strange padding margins
	- but, setting UE4_fullscreenScaleMode to anything "but FIXED scale mode" will work...

	#jira UE-46555  HTML5 game window does not scale with browser size

Change 3988408 by Nick.Shin

	HTML5 call EndSession() onbeforeunload()

	? should PreExit() be called instead?

	#jira UE-57207  Session End event is not generated for HTML5

Change 3991828 by Nick.Shin

	HTML5 shipping build crash

	some FVector2D needs ContainsNaN() checks

	#jira UE-57401  Projects packaged for Shipping HTML5 do not launch the engine in the browser

Change 3992884 by Nick.Shin

	HTML5 call EndSession() onbeforeunload() code cleanup

	#jira UE-57207  Session End event is not generated for HTML5

Change 3992887 by Nick.Shin

	datarouter: Session events code cleanup

	#jira UE-22285 - Session events are not generated for HTML5

Change 4002603 by Sorin.Gradinaru

	UE-56177 Unplugging a device while launching onto it from a source build will result in the "Running..." toast staying open

	#jira UE-56177
	#Android
	#iOS
	#4.10

	Using the device discovery to signal when the running device gets disconnected

Change 4007162 by Dmitriy.Dyomin

	Merging using Dev-Mobile->FortMain
	Added ObjectOrientation material node for decals, returns decal projection direction ( X-axis)
	#jira none

Change 4012196 by Sorin.Gradinaru

	UE-57120 Lighting needs to be rebuilt error appears on Camera test app on Nexus 9 and Note 4.

	#jira UE-57120
	#Android
	#4.20

	Level lightings rebuilt and  QA-Media_Camera_BuiltData.uasset added.

	The message appeared (rarely and only on certain devices) because the engine tries to load the pre-computed lightmap data on the render thread, then to add it to the scene on the game thread (in  FPrecomputedVolumetricLightmap::AddToScene).

	Most of the times there is a desync and the data is not yet loaded when the lightmap is validated (in FScene::AddPrecomputedVolumetricLightmap).

Change 4013034 by Sorin.Gradinaru

	UE-55427 iOS application crashes when suspending and resuming the startup movie in rapid succession

	#jira UE-55427
	#iOS
	#4.20

	Caused by ToggleSuspend waiting for FDefaultGameMoviePlayer::WaitForMovieToFinish()

	Renamed InitialMovie to StartupMovie, including the methods related to the  Android platform.

Change 4015449 by Sorin.Gradinaru

	UE-38306 "Running xxx on yyy" panel Cancel button should terminate app

	#jira UE-38306
	#Android
	#4.10

	Run on device: Pressing Cancel on the "Running..." message should stop the application, if running

	Cancel Android builds using "adb shell am force-stop <bundle_id> <device_id>"

	Note: Using a new AutomationTool command (re-starting the Automation tool after canceling the BuildCookRun task chain) is too slow - takes 3-10 sec depending on the PC configuration.

	AutomationTool is used now only to correctly retrieve the bundle id for each Android device. This is done inside the BuildCookRun command when the application is deployed on the device(s). Cannot simply use the current project's properties to retrieve the bundle id, because when using Launch-> Device Launcher, the user can choose to cook&deploy a different project/texture format, also the user can create & use a profile with multiple devices / with different texture formats.

Change 4016057 by Sorin.Gradinaru

	UE-57845 GitHub 4666 : Pull request clipboard on android

	#jira UE-57845
	#4.20
	#Android

	#4666

	https://github.com/EpicGames/UnrealEngine/pull/4666

	Implemented Clipboard function on Android.

Change 4020229 by Sorin.Gradinaru

	UE-57845 GitHub 4666 : Pull request clipboard on android

	#jira UE-57845
	#Android
	#4.20

	GameActivity.java: moving the methods related to clipboard above the native public declarations

Change 4021188 by Sorin.Gradinaru

	UE-57876 Location accuracy is ignored by ULocationServicesIOSImpl

	#jira UE-57876
	#iOS
	#4.30

	In ULocationServicesIOSImpl::InitLocationServices(ELocationAccuracy Accuracy, float UpdateFrequency, float MinDistance) the first param must be converted to CLLocationAccuracy and used as the first param of LocationDelegateinitLocationServices, rather than using the hardcoded kCLLocationAccuracyHundredMeters.

	Also fixed a compilation error (!) when enabling The Location Services plugin on iOS

Change 4024839 by Sorin.Gradinaru

	UE-38306 "Running xxx on yyy" panel Cancel button should terminate app

	#jira UE-38306
	#Android
	#4.10

	Removed unnecessary #include "AndroidTargetDevice.h", causing circular reference =>  nightly build errors

Change 4024962 by Cosmin.Sulea

	UE-56294 - Packaging step fails when packaging project for distribution

	#jira UE-56294

Change 4026122 by Sorin.Gradinaru

	UE-57149 Razer Phone: Crash after Switching Camera Format 22-26 times

	#jira UE-57149
	#Android
	#4.20

	jobject obj = env->GetObjectArrayElement must be followed by env->DeleteLocalRef(obj)

	The bug can probably be reproduced by using a MediaPlayer.

Change 4038185 by Nick.Shin

	HTML5 - merge error fix

	MallocAnsi.cpp was stomped on

	#jira UE-58367  //UE4/Dev-Mobile - Compile UE4Game HTML5 - use of undeclared identifier 'malloc_usable_size'

Change 4039521 by Dmitriy.Dyomin

	Export WorldBrowser API so plugin makers can use it
	#jira UE-57323

Change 4039523 by Dmitriy.Dyomin

	Exposed MobilePatchingLibrary API
	#jira UE-55941

Change 4039526 by Dmitriy.Dyomin

	Fixed: Hierarchy filtering does not work in world composition
	#jira UE-57900

Change 4039529 by Dmitriy.Dyomin

	Fixed: 'Apply Fogging' in Material does not work on Mobile (GitHub 4357)
	#jira UE-53618
	#4357

Change 4039874 by Sorin.Gradinaru

	UEMOB-436 Support "All Android" Launch On and Project Launcher options

	The main change is in the DeviceProxy class.

	A new type ("All devices" proxy) was added, and the proxy now holds a list of physical device IDs for every variant (texture format), instead of a single device ID.

	The "All devices" proxy is updated automatically by the device discovery thread.

	The change was necessary because the list in the Project Launcher is using the device proxy list.

	#jira UEMOB-436
	#Android
	#UE4
	#4.19

Change 4041446 by John.Mauney

	Fix that Chris B made locally on my machine
	#jira UE-58420

Change 4041791 by Jack.Porter

	Fix CIS incremental UE4Editor Win64

	#jira 0

[CL 4047603 by Jack Porter in Main branch]